### ISSUE TITLE
Only 7 of 8 numbers are displayed

### ISSUE THREAD

**Issue by greatpotoo** [tiuub/KeeOtp2#1]
Hi,

i recently updated from KeeOtp to KeeOtp2.  I had to create a 8 digit OTP which is easy to setup using the custom settings options.
The OTP is created but when it is displayed on screen for manuel entry only 7 of the 8 digits appear.

![694EAE38-5A44-47C7-86A5-9FF5CF396CA6](https://user-images.githubusercontent.com/25334090/106281054-fdc56a80-623e-11eb-88ab-cb9e9d1cbba5.jpeg)

**Comment by tiuub** [comment]
Hello, 

thank you for reporting this issue. It happend due to a basic visual bug. I have fixed it, you can download the fixed version [here](github.com/tiuub/KeeOtp2/releases/latest).

Best regards

**Comment by greatpotoo** [comment]
Thank you very much for making the change so quickly!
