### ISSUE TITLE
"Migration Error!" popup appears for every entry missing an `otp` custom field

### ISSUE THREAD

**Issue by rasa** [tiuub/KeeOtp2#11]
With version 1.5.0, when I select Tools -> KeeOtp2 -> Settings and click the upper left OK button, a popup dialog box appears for every entry that **_doesn't_** have a `otp` custom field. The popup says:
```
---------------------------
Migration Error!
---------------------------
Cant migrate "passwords" - "Entry Name"
(Username: user)

Just check the format of the "key" string.
---------------------------
OK   
---------------------------
```
There is no way to cancel the operation, so I have to click [OK] for every entry. At some point, I got a exception dialog, and the program aborted without updating any of the fields.

**Comment by tiuub** [comment]
I'm working on it!
