### ISSUE TITLE
Manually editing the key or uri doesn't save.

### ISSUE THREAD

**Issue by EvEvans** [tiuub/KeeOtp2#14]
I needed to set up a new TOTP for an account, so the key changed, but when editing this, the first time it doesn't save.

Steps to reproduce:
- Right click an entry which already has a TOTP installed
- Click on "Timed One Time Password"
- Click on "Edit" button
- Change/update the "Key or Uri" entry to the new value
- Click "Ok" button

Expected behaviour:
Save new key and return to previous screen which shows the TOTP for the current time based on the new key.

Actual behaviour:
Both "Configuration" and "Timed Passwords" close. The new key is not saved, and the old one is also deleted.

After this, with an empty configuration, it is possible to save the new key.

**Comment by tiuub** [comment]
Thank you for submitting. I will test it today

**Comment by tiuub** [comment]
Should be fixed now!

**Comment by EvEvans** [comment]
I can confirm it is fixed with the new version. Thanks!
