### ISSUE TITLE
error: method not found

### ISSUE THREAD

**Issue by SD1313** [tiuub/KeeOtp2#15]
Since V1.5.1 i get this error message:

![image](https://user-images.githubusercontent.com/47224147/110751358-0a78ad80-8244-11eb-8651-167308302bfc.png)

**Comment by tiuub** [comment]
Hi,
this looks bad.
Did you already update to 1.5.3?

**Comment by SD1313** [comment]
I tried it again with 1.5.3, but the error looks like the same:

![image](https://user-images.githubusercontent.com/47224147/110817608-bfcf5380-828c-11eb-891a-19bf8244f2b1.png)

**Comment by tiuub** [comment]
Okay, I cant replicate this issue.

Can you run KeePass in Debug-Mode and send me the output?

32-Bit System:
`"%PROGRAMFILES(X86)%\KeePass Password Safe 2\KeePass.exe" --debug`

64-Bit System:
`"%PROGRAMFILES%\KeePass Password Safe 2\KeePass.exe" --debug`

**Comment by SD1313** [comment]
With --debug it show's this message:

![image](https://user-images.githubusercontent.com/47224147/110953471-b1923d80-8347-11eb-8170-9dad4b34b483.png)

**Comment by tiuub** [comment]
Well, that ist weird. Normally it should output a logfile to you.

Just try closing KeePass completely. Then open a cmd (Press WIN + R and type in CMD) and use the command I had posted before.
If the error happens then, you will get a MessageBox which leads to a `*.tmp` file. Click this link, copy the content and post it here.

If this doesn't work. Close KeePass entirely. Open an explorer, navigate to the KeePass installation folder (where KeePass.exe is located. Click in the address bar (where the path is shown, like `C:/Program Files/...`). Replace the whole path with `cmd`. If the CMD opens, type in `KeePass.exe --debug`.

This should give you the log file.

**Comment by SD1313** [comment]
Sorry, i tried it in several ways and also only with your plugin active, but the only message i get is the shown before.
I tried also to find the tmp-file. But didn't found it. (searched in %AppData%, "%PROGRAMFILES(X86)%\KeePass Password Safe 2" and %Temp%)
After the shown message box the plugin is not listet in the loaded plugins window (but i think thats clear ;-) )

I'm using KeePass 2.47 (64bit) on a Windows 10 Pro (20H2).

**Comment by Elenkhos** [comment]
This is a long shot but worth a try if you haven't tried it already. Completely close Keepass and clean the the plugin cache folder for the Keeotp2 in `C:\Users\<username>\AppData\Local\KeePass\PluginCache`. It's probably safe to clean the whole `PluginCache` folder if you want but it might take some time to construct the whole plugin cache again when starting Keepass.

**Comment by SD1313** [comment]
After uninstall and install Keepass, it's working now.
(The --debug switch is not working again, but for the moment it's not necessary ;-) )

One "problem" was that my installation of KeePass (64bit) was in the folder %ProgramFiles(x86)%
With un- and reinstall, it switched to %ProgramFiles% (for 64bit applications)

Thank you for your support!
