### ISSUE TITLE
method not found Int32 OtpSharp.Totp.ComputeTotp()"

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [tiuub/KeeOtp2#17]
I get those error  messages in plugin Version: 1.5.3.0 & Keepass 2.48.1 if pressing the  Keepass global auto type hotkey anywhere

(translates method not found)

```
---------------------------
KeePass
---------------------------
Methode nicht gefunden: "Int32 OtpSharp.Totp.ComputeTotp()".
---------------------------
OK   
---------------------------

```

![grafik](https://user-images.githubusercontent.com/46166740/119187271-a7d43700-ba68-11eb-8b91-94cfa1c64f7d.png)

**Comment by tiuub** [comment]
Hi @4-FLOSS-Free-Libre-Open-Source-Software,

im just kind of busy at the moment. I cant reproduce your error. Ive tried with the same settings, as you described. But for another issue, I have done some coding for the plugin. Therefore I can send you a pre-release. It might fix your problem. Just give it a try and please tell me if it works.

Pre-Release:
[KeeOtp2 - 1.5.3.1(pre).zip](https://github.com/tiuub/KeeOtp2/files/6525298/KeeOtp2.-.1.5.3.1.pre.zip)

**Comment by tiuub** [comment]
Hello @4-FLOSS-Free-Libre-Open-Source-Software,

I have released version 1.5.4 today. It is basically the same like the pre-release, but with some minor bug fixes.
You can check this out too.

So can I close this issue?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> 
> 
> Hallo @4-FLOSS-Free-Libre-Open-Source-Software,
> 
> Ich habe heute Version 1.5.4 veröffentlicht. Es ist im Grunde das gleiche wie in der Vorabversion, jedoch mit einigen geringfügigen Fehlerkorrekturen.
> Sie können dies auch überprüfen.
> 
> Kann ich dieses Problem schließen?


Hi, thanks for the new version I installed it through chocolatey, and unfortunately it still gives me errors. Seems to be a other problem? Not sure how to find more useful information for this error to provide. May any incompatibility? I used to use keepasstraytotp earlier.

```

[Window Title]
KeePass

[Main Instruction]
Trigger-Ausführung fehlgeschlagen

[Content]
Methode nicht gefunden: "Int32 OtpSharp.Totp.ComputeTotp()".

[OK]
```

![grafik](https://user-images.githubusercontent.com/46166740/119407848-5def8900-bcd4-11eb-8738-fa83c43d6614.png)

```

choco install keepass-plugin-keeotp2
Chocolatey v0.10.15
Installing the following packages:
keepass-plugin-keeotp2
By installing you accept licenses for the packages.
Progress: Downloading keepass-plugin-keeotp2 1.5.3... 100%

keepass-plugin-keeotp2 v1.5.3 [Approved]
keepass-plugin-keeotp2 package files install completed. Performing other installation steps.
Downloading keepass-plugin-keeotp2
  from 'https://github.com/tiuub/KeeOtp2/releases/download/v1.5.3/KeeOtp2.plgx'
Progress: 100% - Completed download of C:\Program Files (x86)\KeePass Password Safe 2\Plugins\keepass-plugin-keeotp2.plgx (535.43 KB).
Download of keepass-plugin-keeotp2.plgx (535.43 KB) completed.
Hashes match.
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\keepass-plugin-keeotp2.plgx
 The install of keepass-plugin-keeotp2 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages.

choco install keepass-plugin-keeotp2 --version=1.5.4
Chocolatey v0.10.15
Installing the following packages:
keepass-plugin-keeotp2
By installing you accept licenses for the packages.
Progress: Downloading keepass-plugin-keeotp2 1.5.4... 100%

keepass-plugin-keeotp2 v1.5.4
keepass-plugin-keeotp2 package files install completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was '29D3F15EBF183BBA012E377156D5D63307F8253862EECD1DFC672DD01BA007F5'.
Downloading keepass-plugin-keeotp2
  from 'https://github.com/tiuub/KeeOtp2/releases/download/v1.5.4/KeeOtp2.plgx'
Progress: 100% - Completed download of C:\Program Files (x86)\KeePass Password Safe 2\Plugins\keepass-plugin-keeotp2.plgx (551.73 KB).
Download of keepass-plugin-keeotp2.plgx (551.73 KB) completed.
Hashes match.
C:\Program Files (x86)\KeePass Password Safe 2\Plugins\keepass-plugin-keeotp2.plgx
keepass-plugin-keeotp2 will be loaded the next time KeePass is started.
Please note this plugin may require additional configuration. Look for a new entry in KeePass' Menu>Tools
 The install of keepass-plugin-keeotp2 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages.
```

**Comment by tiuub** [comment]
Okay. That's interesting.

Can you start KeePass in debug mode? Then you will receive a much more detailed debug log.

Therefore you have to navigate to the KeePass installation folder. Run an 'cmd' inside this folder and type in "KeePass.exe --debug". A message box with an clickable path will rise up. Just click the path and paste the content here.

Kind regards

**Comment by tiuub** [comment]
Hi @4-FLOSS-Free-Libre-Open-Source-Software,

I have updated the .NET-Framework to 4.5 and replaced OtpSharp with Otp.NET. This should solve your issue.

I will upload a pre-release here. Please tell me, if it has worked for you. If so, I will uploaded it in production.
[KeeOtp2 - 1.5.5.1(pre).zip](https://github.com/tiuub/KeeOtp2/files/6643885/KeeOtp2.-.1.5.5.1.pre.zip)

Kind regards!

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Hi, thanks for fixing, the provided KeeOtp2 - 1.5.5.1(pre) version did not produce any of the error messages so far and works great for me. 
Best regards

**Comment by tiuub** [comment]
That's great! I will release this version in the following days.

Have a good day!
