### ISSUE TITLE
Cannot configure a new TOTP entry since 1.5.4

### ISSUE THREAD

**Issue by avbfr** [tiuub/KeeOtp2#18]
Hello,
Since last update, every time I try to configure a new TOTP entry, a get this error message: 

_There happened an error. Please check your entered key and your settings!_

_Error message:_
_La référence d'objet n'est pas définie à une instance d'un objet_

Which in english means _Object reference not set to an instance of an object_.

Instead of the TOTP preview abose the key field i've _invalid_. 

I uninstalled keepass, removed langage, kepass.config.xml and other plugins and still having the issue. 

Keepass version is: 2.48.1.
OS Version: Windows 10 Enterprise 20H2
I've Migrated to buit-in all OTP entries and I use {TIMEOTP} Hotkey Sequence.

**If a restore the old 1.5.3 everything works fine.** 

Also : I get used to CTRL-T for TOTP Shortcut and even if I define it in Global Hotkey it doesn't work. 

Thanks for your help.
AVB

**Comment by tiuub** [comment]
Hi, 
thank you for submitting.

I will check it out later.

**Comment by tiuub** [comment]
I have fixed your issue. It was a small typo.

Thank you for your submission!
