### ISSUE TITLE
Cannot assign hotkey to TIMEOTP

### ISSUE THREAD

**Issue by avbfr** [tiuub/KeeOtp2#19]
Hello Again, 

First, thanks for #18 !!

Another (smaller) issue: I cannot assign a HotKey to TIMEOTP. I tried CTRL+T, CTRL+Alt+T, CTRL+Shift+T, I just get an error beep and nothing happens.

_Use global Hotkey_ is, of course, enabled.

I also found more conveniant to have to _Copy TOTP_ Option bellow _Copy Username_ and Copy _Password_ Menus than in the KeeOtp2 Submenu. Would it be possible to have an option to show/hide it ?

Thanks again for this great plugin !
AVB

**Comment by tiuub** [comment]
Hi @avbfr,


thank you for your feedback. The "Copy TOTP" thing should be an easy one, I will implement with the next patch. 
Your mentioned bug may be based on the implementation of NHotkey. I will check this out. Thank you!

**Comment by avbfr** [comment]
Hello @tiuub,
Thanks !
Just to clarify a little: I'm able to Assign the HotKey in the config menu but When I try to use it I get the error beep.and the TOTP is not copied.

**Comment by tiuub** [comment]
Hi @avbfr,

I tried to reproduce your error, but Im not able to get it. Can you give me some more details about your environment?
Which version of Windows do you use? Which system type do you run, 32-bit or 64-bit? Do you use any other software which handles hotkeys, like AutoHotkey or anything else?

**Comment by avbfr** [comment]
Hello @tiuub
I'm using Windows 10 Enterprise 20H2 64 Bits. I've AutoHotkey installed but it's not activated. 
Other Standard KeePass Hotkeys are working fine (CTRL+B, CTRL+V...).
CTRL+T for TOTP stopped working with 1.5.4. I've also tried to set different HotKey but none are working (CTRL+T, CTRL+Alt+T, CTRL+Shift+T).

Other KeePass plugins: KeeAgent 0.12.1.0, KeeChallenge 1.5.0.0, KeePassQRCodeView 1.0.4.0
KeePass Version: 2.48.1 (Latest)

Hope this help.
AVB

**Comment by tiuub** [comment]
Okay, thank you. I have tweaked a little bit around. Please check out the newes pre release.

[KeeOtp2 - 1.5.4.2(pre).zip](https://github.com/tiuub/KeeOtp2/files/6556771/KeeOtp2.-.1.5.4.2.pre.zip)

Please tell me, if it worked for you.

**Comment by avbfr** [comment]
Just tested and CTRL+T works !! Also it's Good to have Copy TOTP under Copy Password ! :-) **Thanks a lot !!**

On this version, I just noticed a small delay (about 1.5s) when copying TOTP using HotKey or directly by clicking on "Copy TOTP" (My KeePass window reduce automatically when I use such menus that's how I can notice the delay).

The configurable Global HotKey looks to not be used anymore but I assume that's the tweak you made. ;-)

AVB

**Comment by tiuub** [comment]
Great! I will check the issue with the delay. 

The Global Hotkey is still usable. It's similar to the built-in Ctrl + Alt + A hotkey. If configured, you can instantly paste the TOTP into the target window by hitting Ctrl + Alt + T. You can configure this at "Edit Entry" - "Auto-Type". For example you configure Auto-Type with window title "*Google*", then hop over to the browser, open Google-Login and hit Ctrl + Alt + T. The TOTP should be pasted right now.

But for now, I will close this issues.
