### ISSUE TITLE
Hotkey for OTP only auto-type

### ISSUE THREAD

**Issue by Elenkhos** [tiuub/KeeOtp2#2]
Hi,

Could you add a global hotkey to auto-type only the {TIMEOTP} placeholder. For example, KeePassOTP has this feature but it uses its own placeholder not the default Keepass placeholder.

I know that I can use {TIMEOTP} placeholder in custom auto-type sequence but I would like to have a dedicated hotkey to type only the {TIMEOTP} placeholder.

Thank you for considering.

**Comment by tiuub** [comment]
Hi,

thank you for submitting your feature request. I will check this out and try to implement this.

Just give me some time. I will give my best!

**Comment by tiuub** [comment]
I have implemented a HotJey option. It's activated by default. You can use it with CTRL-ALT-T, but you can also use another key combination.

**Comment by Elenkhos** [comment]
Hi,

Thanks for this. Unfortunately, it seems that changing the TOTP keystroke sequence (for example {TOTP}{ENTER}) disables my global auto-type hotkey (!).

KeeOtp2 1.5.2 and Keepass 2.4.7.

**Comment by tiuub** [comment]
Hi,

thank you for your feedback. I will test this today.

**Comment by Elenkhos** [comment]
I can confirm that setting the custom TOTP keystroke sequence doesn't disable the global auto-type hotkey anymore in version 1.5.3. Thank you!

**Comment by Gerd-MUC** [comment]
No TOTP hotkey works on my sytem - not the global CTRL-ALT-T and also no individual. I try more combinations with CTRL+SHIFT+'a Letter'. 
I'm using KeePaas 2.47 (64bit), German.lngx, KeeOtp2

**Comment by tiuub** [comment]
Hi @Gerd-MUC ,

which version of KeeOtp2 and which OS are you using? Are you able to use KeePass defined hotkeys, like CTRL + ALT + a?

**Comment by Gerd-MUC** [comment]
Thanks for feedback - and for the nice tool. 👍
I use KeeOtp2 1.5.3.0 in Windows 10 20H2 Built 19042.868 (all Updates from this weekend).
Now, I test with ALT+CTRL+Z or ALT+CTRL+I - not HotKey-Output. I can't configure ALT+CTRL+A.
It may also be important: I uese KeePass Portabel and my User Accout has only Nomal-User-Privilegs - no Admin.

**Comment by tiuub** [comment]
Sorry for my late answer @Gerd-MUC .

I didn't want you to set this combination for TOTP hotkey. I want to know, if you are able to use the main auto type. So does it output your username and password in a window if you press `CTRL + ALT + A`? 

It's important to know, because I'm using the KeePass built-in hotkey function. This means, if the built-in function does not work, the hotkey of this plugin won't work too.
