### ISSUE TITLE
Any chance of adding Steam guard support?

### ISSUE THREAD

**Issue by homever** [tiuub/KeeOtp2#20]
Used for a while, thank you for your work.
 Any chance to see the integration of Steam guard TOTP? Thank you.

**Comment by tiuub** [comment]
Sure. This is already planned. You can estimate it in about 2 or 3 weeks.

Kind regards

**Comment by DigitalDJ** [comment]
There's a pull request for Steam Guard support up at the moment. Wish I would have read this thread beforehand ;-)

**Comment by tiuub** [comment]
Hi @homever,

I have just uploaded a patch  for steam support.
Just give it a try. Its version 1.5.6.

Kind regards

**Comment by homever** [comment]
@tiuub Confirmed working! 
Thank you so much for this addon 👯

**Comment by Zickfor** [comment]
You are talking about Valves Steam? How did you get secret?

**Comment by homever** [comment]
@Zickfor I use [https://github.com/Jessecar96/SteamDesktopAuthenticator](url)

**Comment by OchreFox** [comment]
Wanted to give a quick tutorial on how to setup Steam guard:

1. Remove Steam Guard mobile authenticator (if present)
2. Download latest release from [Steam Desktop Authenticator](https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/latest)
3. Run the exe and set up a new account, follow the instructions given on screen
4. Optionally leave blank encryption field _(we just need to get the uri from the generated data)_
5. After setting up the account, open the folder where the Steam Desktop Authenticator app is
6. Open the file with extension .maFile _(/SDA-x.x.xx/maFiles/*****.maFile)_ as a text file with Notepad or Notepad++ _(This is actually a JSON File)_
7. Copy the uri value _(starting with "otpauth://", without quotation marks)_
8. Open Keepass and configure the TOTP
   - Paste the uri in the Uri field
   - Check the "Use Custom Settings" option
   - In general > Type, select Steam
10. The preview should now give an identical code to the one in the SDA app
11. Save and done!
