### ISSUE TITLE
CTRL+T no longer copies TOTP code

### ISSUE THREAD

**Issue by ybkshaw** [tiuub/KeeOtp2#21]
Previously I was able to use CTRL+T to copy the TOTP code, as of this latest version that option doesn't seem to exist. CTRL+B copes the Username field, CTRL+C copies the Password field, no CTRL+T.

**Comment by tiuub** [comment]
Hi @ybkshaw,

this happened because I have rearranged the items in entries context menu.

I have fixed it in a pre-release.

[KeeOtp2 - 1.5.4.2(pre).zip](https://github.com/tiuub/KeeOtp2/files/6556771/KeeOtp2.-.1.5.4.2.pre.zip)

**Comment by ybkshaw** [comment]
Confirmed that fixes the issue, thanks kindly!

**Comment by fantastory** [comment]
yeep it works :) 
please push to production to avoid confusions,
I checked all others otp plugins and they do not have this feature
