### ISSUE TITLE
does not recognize complex codes where the time is different from 30 seconds.

### ISSUE THREAD

**Issue by OmlineEditor** [tiuub/KeeOtp2#22]
poorly recognizes codes where non-standard time values and non-standard values of numbers. you only have 6 and 8 numbers in the token, but I have both 7 and 9 numbers. your plugin doesn't support it.

See QR. Dig=8, time=35 sec. but your plugin puts 6 digits and 30 sec.
![bug](https://user-images.githubusercontent.com/13348933/121088277-28778f00-c7ee-11eb-8329-bb1ce0f678f4.jpg)

**Comment by tiuub** [comment]
Hey,
thank you for your submission.

Currently Im a little bit stressed, but Im working on it.

**Comment by tiuub** [comment]
I have commited a fix for your issue. I had a typo in my code, so custom periods were not recognized. Also it is now possible to set a custom amount of digits. 

Kind regards!
