### ISSUE TITLE
Can we have 7 digits also instead of only 6 or 8?

### ISSUE THREAD

**Issue by patrick258** [tiuub/KeeOtp2#25]
Authy is using a 7 digits, 10 second TOTP scheme and I would like to get rid of this additional app. However KeeOTP only offers 6 or 8 digits code option.

https://gist.github.com/JacobJohansen/5f688d45049be440b8ee87cc5e854b75

**Comment by tiuub** [comment]
Hi @patrick258,

please try the newest version 1.5.5. There I have implemented this feature.

Kind regards

**Comment by patrick258** [comment]
Thanks, works like a charm
