### ISSUE TITLE
still not working CTRL+T 

### ISSUE THREAD

**Issue by cyberseguranca** [tiuub/KeeOtp2#26]
I tested the new version 1.5.5 and it **still doesn't work**  CTRL+T to copy the TOTP .

![image](https://user-images.githubusercontent.com/85848764/121821855-9fe86b00-cc93-11eb-98a5-e3a457539137.png)

It only works when clicking on the "Copy TOTP" menu in the image below.

![image](https://user-images.githubusercontent.com/85848764/121821985-6fed9780-cc94-11eb-8f08-62365b202e63.png)

**Comment by tiuub** [comment]
Oh no! Fixed one issue and opened another. Give me some time, I will see what I can do tomorrow. I'm busy right now, but I think it's only a small typo.

Stay tuned, I'm working on it. 

Kind regards!

**Comment by gabycmc** [comment]
Following.  My Ctrl A is not working. Hoping it's the same fix.  Other commands do work. Just not Ctrl + A.

**Comment by cyberseguranca** [comment]
Version v1.5.6.1 same Issue...
