### ISSUE TITLE
Last Modification Time is not updated in the column

### ISSUE THREAD

**Issue by plorerfisfct** [tiuub/KeeOtp2#31]
**Tested version:**
1.5.6.1 - KeeOtp2.plgx - SHA512 392768226901D4EDB227064D92FCE66BADE565DA35074B7F2BDB7F31D9C146EA8D2AC818549F498C39174FA4A2A03E94843D1E4F7E34DFB2614CE1C46E30E8B2

**Windows version:**
Windows 8.1

**Description:**
Hi,

see the screenshots.

![1](https://user-images.githubusercontent.com/87186277/125079228-a8319b80-e0c3-11eb-81a1-32e04ed3581e.PNG)
![2](https://user-images.githubusercontent.com/87186277/125079241-abc52280-e0c3-11eb-9d95-0c427446effc.PNG)
![3](https://user-images.githubusercontent.com/87186277/125079269-b2ec3080-e0c3-11eb-826d-51a34e4a595d.PNG)

**Problems:**

The current KeePass 2.48.1 (64-bit) is used.

When configuring KeeOtp2 successfully, Last Modification Time is not updated in the column. Only in entry view it is updated.

Is this a bug in KeePass or in KeeOtp2?

**Comment by tiuub** [comment]
Hey @plorerfisfct,

it seems to be a bug inside KeeOtp2. As I said before, I will get my eyes on it on Friday.

Kind regards
tiuub

**Comment by tiuub** [comment]
Hi @plorerfisfct,

I have to apologize, I'm very busy right now and can't get any time for coding. I won't forget your issue.

Stay tuned, next update will come soon.

Kind regards
tiuub

**Comment by tiuub** [comment]
Fixed it. You can check out the newest update of KeeOtp2.

Kind regards
tiuub
