### ISSUE TITLE
Dark Theme Compatibility

### ISSUE THREAD

**Issue by isarrider** [tiuub/KeeOtp2#32]
Hi...
with the KeeTheme Plugin (set to dark)
basically almost nothing is readable...

Thx,
ALex

**Comment by tiuub** [comment]
Hi @isarrider,

thank you for your issue. I didn't run into this issue ever before, because I'm using plain theme for KeePass.

As I said in another issues before, I'm not at home right now, so I'm not able to fix this immediately. Please stay patient, I won't forget your issue.

Kind regards
tiuub

**Comment by isarrider** [comment]
Hi tiuub - more the other way rounds...
Thanks for your plgin and outstanding support effort!

BR,
ALex

**Comment by isarrider** [comment]
awesome - thank you!
