### ISSUE TITLE
Local Shortcut conflig with other plugin, can we change Local Shortcut?

### ISSUE THREAD

**Issue by cheatmo** [tiuub/KeeOtp2#34]
Hi!

I have another plugin also has shortcut key of Ctrl + T for their job. Unfortunately, this plugin has not been developed anymore. Can we have an option to allow changing Ctrl + T shortcut to customer one, just like the global shortcut key? 

Thank you so much!

**Comment by tiuub** [comment]
Hey @cheatmo,

sure, this should be an easy one. 
I'm very busy at the moment. Please stay patient.

Kind regards
tiuub

**Comment by tiuub** [comment]
Hello @cheatmo, 

I have implemented your enhancement. 
Check out the new version 1.5.8.

Kind regards
tiuub

**Comment by cheatmo** [comment]
Work beautifully!
Thank you so much!
