### ISSUE TITLE
Copy TOTP won't work for Steam

### ISSUE THREAD

**Issue by Silun** [tiuub/KeeOtp2#35]
For Steam, the TOTP can only be coped to clipboard by going to `Rightclick -> KeeOtp2 -> Show TOTP -> Copy`. It will not be copied by either `CTRL+T` or `Rightclick -> KeeOtp2 -> Copy TOTP`. Again, to be really clear, it will NOT copy the TOTP when I choose the Copy TOTP option. It only works when I open the little window where it displays the TOTP, and click the copy button there. I have found no other way to get the TOTP to the clipboard.

By contrast, other configurations work. But as soon as I set the type to Steam, it doesn't work any more.

KeePass 2.49, KeeOtp2 1.5.7

**Comment by tiuub** [comment]
Hey @Silun,

thank you for your bug report. I will resolve this as soon as possible. Stay tuned!

Kind regards
tiuub

**Comment by tiuub** [comment]
Hey @Silun,

I have fixed it in the newest version.
Check out version 1.5.8.

Kind regards
tiuub
