### ISSUE TITLE
Exception thrown when setting global hotkey to none

### ISSUE THREAD

**Issue by zeeh1975** [tiuub/KeeOtp2#43]
Setting global hotkey to 'none' even when "Use global hotkey" is unchecked leads to KeePass to thrown an exception message.
Also after reopening KeePass also shows a message about plugin incompatibility, but plugins works anyway.

Config screen:
![KeePass_6fYhMcRXmz](https://user-images.githubusercontent.com/1238547/157484493-9cedeb91-821c-4ff5-b94d-bcfb1e694013.png)

Exception at KeePass start:
![KeePass_xbT8tkR7u7](https://user-images.githubusercontent.com/1238547/157484509-45f139ad-d843-408e-bc96-db81141fb404.png)

**Comment by tiuub** [comment]
Hey, fixed this in the newest version [1.5.9](https://github.com/tiuub/KeeOtp2/releases/tag/v1.5.9).

Kind regards
tiuub
