### ISSUE TITLE
Dialog windows are hidden under keypass window when 'Always on top' is enabled

### ISSUE THREAD

**Issue by denifednu** [tiuub/KeeOtp2#5]
Thank you for making this plugin.

I migrated from KeeOtp to KeeOtp2.  None of the KeeOtp2 dialog window display, instead the focus goes to a window that I cannot see and cannot interact with.

I switched off View -> 'Always on top' and now the KeeOtp2 dialog windows appear.  Naturally, the keypass window now doesn't stay on top of other windows, which is a pain for me.

This issue doesn't occur with the original KeeOtp.

Please try and fix it, thanks for your consideration.

**Comment by tiuub** [comment]
Hi,
thank you for submitting.
I have fixed your problem quickly.
I will attach a pre-release to this comment here, which you can use.

The bug will completely implemented with the next update, which is planned this or next week.

Quick fix (pre-release):
[KeeOtp2 - 1.4.1.1(pre).zip](https://github.com/tiuub/KeeOtp2/files/5944331/KeeOtp2.-.1.4.1.1.pre.zip)

**Comment by denifednu** [comment]
Sorry for not responding sooner, I didn't get a notification.
Thank you very much for fixing this, working great for me.
