### ISSUE TITLE
handle lowercase secret keys

### ISSUE THREAD

**Issue by nigelhooper** [tiuub/KeeOtp2#8]
Hi,
  Some of my secret keys are in lowercase and so when I try to import them I get an error message title: "Illegal character found!" message "The key includes illegal characters" the allowed characters and regex below are all uppercase and so it appears it only accepts uppercase characters.  Would it be possible to automatically handle secret keys that are provided in lowercase?

![illegal character](https://user-images.githubusercontent.com/10681256/109698054-ddaf0100-7b86-11eb-8424-e6b1ea5c4409.jpg)

**Comment by tiuub** [comment]
Hi,
thank you for your feedback. 
There will be an update today. This will fix this issue.
