### ISSUE TITLE
Button refers to non existing web address

### ISSUE THREAD

**Issue by EvEvans** [tiuub/KeeOtp2#9]
When going to Context Menu (right click) -> Timed One Time Password -> Wrong? (button) ->Check the troubleshooting website (button), the last button refers to a non existing web address, legacy of version 1 of the KeeOtp plugin.

Thanks for your plugin, frequent user here!

**Comment by tiuub** [comment]
Hi,
thank you for submitting. 
Well, you are incredible fast. Only two hours after release, you have found the first bug. That's nearly an record. ;)

I'm working on it, I will fix this in the next "bigger" update.

**Comment by EvEvans** [comment]
Haha, thanks. Would love to take credit, but to be honest I was still using the old version 1.4.1.0, and I didn't notice there was an update. Going to upgrade now :)
